# Simulate deployed service for local testing.
FROM us-west1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/python313

COPY --from=us-west1-docker.pkg.dev/mlb-standings-001/artifacts/mlb-standings-001-update /workspace /workspace

ENV PYTHONPATH=/workspace/.venv/lib/python3.13/site-packages
ENV PATH=/workspace/.venv/bin:$PATH

CMD ["serve"]
