# from cloudevents.http import CloudEvent
# from functions_framework.background_event import BackgroundEvent as BackgroundEvent
# from functions_framework.exceptions import EventConversionException as EventConversionException
# from google.cloud.functions.context import Context
# from typing import Any, Tuple
#
# def background_event_to_cloud_event(request) -> CloudEvent: ...
# def is_convertable_cloud_event(request) -> bool: ...
# def cloud_event_to_background_event(request) -> Tuple[Any, Context]: ...
# def marshal_background_event_data(request): ...
