# class FunctionsFrameworkException(Exception): ...
# class InvalidConfigurationException(FunctionsFrameworkException): ...
# class InvalidTargetTypeException(FunctionsFrameworkException): ...
# class MissingSourceException(FunctionsFrameworkException): ...
# class MissingTargetException(FunctionsFrameworkException): ...
# class EventConversionException(FunctionsFrameworkException): ...
