from typing import Tuple

from _typeshed import Incomplete

from google.auth.credentials import Credentials

# def load_credentials_from_file(filename, scopes: Incomplete | None = ..., default_scopes: Incomplete | None = ..., quota_project_id: Incomplete | None = ..., request: Incomplete | None = ...): ...
# def load_credentials_from_dict(info, scopes: Incomplete | None = ..., default_scopes: Incomplete | None = ..., quota_project_id: Incomplete | None = ..., request: Incomplete | None = ...): ...
# def get_api_key_credentials(key): ...
def default(scopes: Incomplete | None = ..., request: Incomplete | None = ..., quota_project_id: Incomplete | None = ..., default_scopes: Incomplete | None = ...) -> Tuple[Credentials, str | None]: ...
