# CI tests

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6.3.1
      with:
        enable-cache: true
    - run: uv python install
    - name: requirements.txt
      run: |
        if ! uv export --frozen --no-hashes --format requirements-txt | cmp -s requirements.txt -; then
          echo "Re-run uv export --frozen --no-hashes --format requirements-txt > requirements.txt"
          exit 1
        fi
    - run: uv sync --frozen
    - name: pytest
      run: uv run --frozen pytest
